
server:
  port: 8887

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: estudiante-api
          uri: http://localhost:8585/
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<service>.*), /$\{service}

        - id: regescapp
          uri: http://localhost:4200/
          predicates:
            - Path=/regesc/**
          filters:
            - RewritePath=/regesc/(?<service>.*), /regesc/$\{service}

#        - id: webapp
#          uri: http://localhost:4201/
#          predicates:
#            - Path=/web/**
#          filters:
#            - RewritePath=/web/(?<service>.*), /web/$\{service}
